version: '3.7'
services:
  php:
    build:
      context: ${DOCKER_NODE_FOLDER_API_BASE_PATH:-.}
      dockerfile: ./devops/docker/php/Dockerfile
    container_name: php
    command: ["php",  "-S", "0.0.0.0:8888",  "-t", "/app/public", "/app/public/index.php"]
    volumes:
      - ${DOCKER_NODE_FOLDER_API_BASE_PATH:-.}:/app
    working_dir: /app
    ports:
      - "${DOCKER_NODE_FOLDER_API_PORT_PREFIX:-2}000:8888"
#    user: "${UID}:${GID}"


