version: "3.7"

services:
  phpsf5:
    ports:
      - 8000:8000

  phpsf4:
    ports:
      - 8001:8000

  supervisor:
    ports:
    - 9001:9001

  # elasticsearch server (official image)
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: elasticsearch:6.8.8 # 6.8.4 out
    ports:
      - 9209:9200

  # elasticsearch head manager (fork of mobz/elasticsearch-head for elasticsearch 6)
  # /!\ it isn't an official image /!\
  # https://hub.docker.com/r/tobias74/elasticsearch-head
  elasticsearch-head:
    container_name: sb-elasticsearch-head
    depends_on:
      - elasticsearch
    image: tobias74/elasticsearch-head:6
    ports:
      - "9109:9100"

  kibana:
    image: kibana:6.8.8
    volumes:
    - ./Devops/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - 5601:5601
    depends_on:
      - elasticsearch

  rabbitmq:
    ports:
      - 15672:15672
