version: "3.7"

x-volumes: &volumeAnchor
  volumes:
    - ${PWD}/:/var/www/
    - ${ARCHIVE_PATH}:${ARCHIVE_PATH}
    - ./App/Symfony5/config/supervisor/messenger-worker.conf:/etc/supervisor.d/messenger-worker.ini
    - ./Devops/supervisord/supervisord.conf:/etc/supervisord.conf

x-image: &image
  image: yemistikris/docker-sapar:base

x-log: &log
  logging:
    driver: json-file
    options:
      max-size: 10m

services:
  phpsf5:
    depends_on:
      - rabbitmq
      - elasticsearch

  supervisor:
    <<: *image
    working_dir: /var/www/App/Symfony5
    <<: *volumeAnchor
    command: [ '/usr/bin/wait-for-it.sh', '--timeout=60', 'rabbitmq:5672', '--', "supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf" ]
    <<: *log
    environment:
      - NB_ID3_CONSUMER=${NB_ID3_CONSUMER}
    <<: *log
    depends_on:
      - rabbitmq
      - phpsf5

  # elasticsearch server (official image)
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: elasticsearch:6.8.8 # 6.8.4 out
    volumes:
      - elsatic_data:/usr/share/elasticsearch/data
    <<: *log
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    <<: *log
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/sapar_index

volumes:
  elsatic_data:
    driver: local