version: "3.7"

x-volumes: &volumeAnchor
  volumes:
    - ${PWD}/:/var/www/
    - ${ARCHIVE_PATH}:${ARCHIVE_PATH}
    - ./App/Symfony5/config/supervisor/messenger-worker.conf:/etc/supervisor.d/messenger-worker.ini
    - ./Devops/supervisord/supervisord.conf:/etc/supervisord.conf
x-image: &image
  image: yemistikris/docker-sapar:base

services:
  phpsf5:
    <<: *image
    working_dir: /var/www/App/Symfony5
    <<: *volumeAnchor
    command: ["symfony", "server:start"]
    depends_on:
      - rabbitmq
      - elasticsearch

  phpsf4:
    <<: *image
    working_dir: /var/www/App/Symfony4
    <<: *volumeAnchor
    command: ["symfony", "server:start"]

  supervisor:
    <<: *image
    working_dir: /var/www/App/Symfony5
    <<: *volumeAnchor
    command: [ '/var/www/Devops/scripts/wait-for-it.sh', '--timeout=60','rabbitmq:5672', '--', "supervisord", "--nodaemon", "--configuration", "/etc/supervisord.conf" ]
    environment:
      - NB_ID3_CONSUMER=${NB_ID3_CONSUMER}
    depends_on:
      - rabbitmq
      - phpsf5

  # elasticsearch server (official image)
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: elasticsearch:6.8.8 # 6.8.4 out
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"

  # elasticsearch head manager (fork of mobz/elasticsearch-head for elasticsearch 6)
  # /!\ it isn't an official image /!\
  # https://hub.docker.com/r/tobias74/elasticsearch-head
  elasticsearch-head:
    container_name: sb-elasticsearch-head
    depends_on:
      - elasticsearch
    image: tobias74/elasticsearch-head:6

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/sapar_index
