# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        media_index:
            types:
                media:
                    properties:
                        filePath:
                        hash: ~
                        title: ~
                        artist:
                            type: keyword
                        bpm:
                            type: double
                        genre:
                            type: keyword
                        year:
                            type: integer
                    persistence:
                        driver: orm
                        model: Sapar\Component\AudioCoreEntity\Entity\Media