# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            types:
                media:
                    properties:
                        filePath: ~
                        hash: ~
                        title: ~
                        artist: ~
                        bpm: ~
                        year: ~
                    persistence:
                        driver: orm
                        model: AudioCoreEntity\Entity\Media