<?php

namespace AudioCoreEntity\Repository;

use AudioCoreEntity\Entity\Media;
use AudioCoreEntity\Entity\RadioHit;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Base;
use Doctrine\Persistence\ManagerRegistry;

/**
 * RadioHitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioHitRepository extends CoreRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getClassMetadata(RadioHit::class));
    }
    /**
     * @param $minSimilarity
     * @param $artist
     * @param $title
     * @return RadioHit[]
     */
    public function getSimilar($artist, $title, $minSimilarity = 51)
    {
        $query = $this->_em->createQuery('SELECT r FROM RadioHit r WHERE LEVENSHTEIN_RATIO(CONCAT(r.artist, \' \', title), :artistTitle) > :minSimilarity');
        $query->setParameter('artistTitle', sprintf('%s %s', $artist, $title));
        $query->setParameter('minSimilarity', $minSimilarity);

        return $query->getResult();
    }
}
