<?php

declare(strict_types=1);

/**
 * This file is part of the Sapar project.
 * @author Christophe Pyree <pyrex-fwi[at]gmail.com>
 */

namespace AudioCoreEntity\Repository;

use AudioCoreEntity\Entity\RadioHit;
use Doctrine\ORM\EntityManagerInterface;

/**
 * RadioHitRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RadioHitRepository extends CoreRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, $em->getClassMetadata(RadioHit::class));
    }

    /**
     * @return RadioHit[]
     */
    public function getSimilar(string $artist, string $title, int $minSimilarity = 51)
    {
        $query = $this->_em->createQuery('SELECT r FROM RadioHit r WHERE LEVENSHTEIN_RATIO(CONCAT(r.artist, \' \', title), :artistTitle) > :minSimilarity');
        $query->setParameter('artistTitle', sprintf('%s %s', $artist, $title));
        $query->setParameter('minSimilarity', $minSimilarity);

        return $query->getResult();
    }
}
