language: php

php:
  - '5.6'
  - '7.0'

#matrix:
#  allow_failures:
#    - php: 7.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python -y
  - sudo apt-get install  -y mediainfo
  - sudo apt-get install  -y id3v2
  - sudo apt-get install  -y flac
  - whereis mediainfo
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python get-pip.py
  - sudo pip install eyeD3
  - sudo pip show eyeD3
  - /usr/local/bin/eyeD3 --version || true

install:
  - composer install
