name: Grump

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: ./Component/audio-core-entities
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: AudioCore DB init
      run: php vendor/bin/doctrine orm:schema-tool:update -n --dump-sql --force
      working-directory: ./Component/audio-core-entities

    - name: Qa
      run: php vendor/bin/grumphp run --testsuite qa -vvv
      working-directory: ./Component/audio-core-entities
